[package]
org = "ballerina"
name = "url"
version = "@toml.version@"
authors = ["Ballerina"]
keywords = ["url encoding", "url decoding"]
repository = "https://github.com/ballerina-platform/module-ballerina-url"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.8.0"

[platform.java21]
graalvmCompatible = true

[[platform.java21.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "url-native"
version = "@toml.version@"
path = "../native/build/libs/url-native-@project.version@.jar"
